### ISSUE TITLE
[BUG]: An index error occurs in the single scene rendering example.

### ISSUE THREAD

**Issue by slickker** [yinyunie/BlenderProc-3DFront#6]
**Describe the bug**
I followed the README.
I downloaded the textures and received all 1814 of them.
'blenderproc run blenderproc/scripts/download_cc_textures.py ./resources/cctextures'

However, when I run the following line, the length of cc_materials is 0.
cc_materials = bproc.loader.load_ccmaterials(args.cc_material_folder, ["Bricks", "Wood", "Carpet", "Tile", "Marble"])

So, an index error occurs in the single scene rendering example. (I use traceback)
Traceback (most recent call last):
  File "/home/user/workspace/BlenderProc-3DFront/examples/datasets/front_3d_with_improved_mat/render_dataset_improved_mat.py", line 156, in <module>
    floor.set_material(i, random.choice(cc_materials))
  File "/home/user/blender/blender-3.0.0-linux-x64/3.0/python/lib/python3.9/random.py", line 346, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

**General Information**
1. Which BlenderProc version are you using?
commit 4cc055f1ce8342bf25bc11e116ab9ee36a5a277c
(Latest version as of now)

2. On which operating system are you?
ubuntu 20.04

3. Have you checked the issue tracker to see if a similar issue has been opened?
Yes, there are no similar cases.

4. Have you changed BlenderProc in any way besides the config file? If yes, are you sure that this change does not affect the problem you are having?
I'm not changed.

**To Reproduce**
1. Provide the full command you used to run BlenderProc:
`blenderproc run \
examples/datasets/front_3d_with_improved_mat/render_dataset_improved_mat.py \
examples/datasets/front_3d_with_improved_mat/3D-FRONT \
examples/datasets/front_3d_with_improved_mat/3D-FUTURE-model \
examples/datasets/front_3d_with_improved_mat/3D-FRONT-texture \
6a0e73bc-d0c4-4a38-bfb6-e083ce05ebe9.json \
resources/cctextures/ \
examples/datasets/front_3d_with_improved_mat/renderings`

2. Provide the full python file, you used:
```python

```
3. Provide a link to all 3D models you used, if they are from one of the publicly available supported datasets, provide the name or path so that it is possible to reproduce the error.
https://tianchi.aliyun.com/specials/promotion/alibaba-3d-scene-dataset

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by slickker** [comment]
I found the reason.
I debugged it and modified it as follows:

In CCMaterialLoader.py, Line 69
base_image_path = os.path.join(current_path, "{}_2K_Color.jpg".format(asset))
to
base_image_path = os.path.join(current_path, "{}_2K-JPG_Color.jpg".format(asset))
